#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_home:
  path: /
  controller: App\Controller\Home::index

#SignUpForm:
#  path: /Account/SignUp/Form
#  controller: App\Controller\Account\SignUpController::form

#
#app_lucky_number:
#  path: /lucky/number
#  controller: App\Controller\LuckyController::index